# config.yaml
run_id: run_001
input_pdb: inputs/protein_complex.pdb

#Strip any non-protein resdiues
strip_hetero: true
strip_waters: true
keep_residues: [] #Prevents the stripping of specified residues 
#Splitting the protein_complex into chain A and B
receptor_chain: B 
ligand_chain: A #nanobody

#Forcefield:
forcefield: leaprc.protein.ff14SB
water_model: TIP3PBOX
box_padding_ang: 12.0 #derived from tutorial

#Equilibration parameters
restraint_weight: 10.0
heat1_steps: 25000            
target_temp: 300.0
heat2_taup: 1.0
heat3_taup: 2.0
equil_ps: 500

#Production
production_ns: 100 #run-time parameter 
random_seed: -1 #ensures reproducability by using -1 value stated in tutorial

#Convergence threshold
density_tol_pct: 1.0
rmsd_slope_tol: 0.0005
rmsd_stride: 10 #Checks every 10 frames for convergence

#Compute Selection GPU vs CPU dependent on simulation
use_gpu: true
engine_equil: "pmemd.cuda"      # heat/density/equil run on GPU
engine_prod: "pmemd.cuda"       # production runs on GPU
min_engine_override: "sander"   # minimization forced to CPU regardless of engine_equil
modules:                        # keep this list in sync with your sbatch scripts
  - amber/22
  - cuda/12.2
  - python/3.11